#!/usr/bin/env python3

import os, sys

_src_dir = '%s/src/' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _src_dir))

if sys.version_info[0] == 3:
    import yypget
    if __name__ == '__main__':
        yypget.main()
else:
    print('[fatal] Python 3 is required')
